#!/bin/bash

# Display Hatboy ASCII Art
printf "\e[1;92m        _____  \e[0m\n"
printf "\e[1;92m       /     \ \e[0m\n"
printf "\e[1;92m      | () () |\e[0m\n"
printf "\e[1;92m       \  ^  / \e[0m\n"
printf "\e[1;92m        |||||  \e[0m\n"
printf "\e[1;92m        |||||  \e[0m\n"
printf "\e[1;77m     __/_____\__ \e[0m\n"
printf "\e[1;77m    |___________| \e[0m\n"
printf "\e[1;77m     MISTER  X \e[0m\n"

# Start Flask Web Server in the Background
echo "Starting the local Flask web server..."
python3 hatboy_server.py &

# Wait for Flask to initialize
sleep 3

# Start Cloudflare Tunnel Automatically
echo "Starting Cloudflare Tunnel..."
cloudflared tunnel run hatboy &

# Wait for Cloudflare to initialize and fetch the public URL
sleep 5

# Fetch the live URL generated by Cloudflare
echo "Fetching the live URL from Cloudflare logs..."
CLOUDFLARE_URL=$(cloudflared tunnel list | grep hatboy | awk '{print $4}')

if [[ -n "$CLOUDFLARE_URL" ]]; then
    echo -e "\nYour site is live at: \e[1;92m$CLOUDFLARE_URL\e[0m"
else
    echo -e "\n\e[1;91mERROR:\e[0m Could not retrieve the live URL. Check Cloudflare Tunnel logs."
fi
